### ISSUE TITLE
Error: Cannot find module 'react-dev-utils/crossSpawn'

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Voting_DApp#12]
Run:

```
cd frontend
npm install
npm run start

```
Error:

`Error: Cannot find module 'react-dev-utils/crossSpawn'`

**Comment by Arch222** [comment]
Run npm install first

**Comment by Bhaney44** [comment]
> Run npm install first

I did - I ran the syntax as stated in the issue.

**Comment by Bhaney44** [comment]
Fixed. 

delete 

`node_modules
`

then run. 

```
npm install
npm run start
```
