### ISSUE TITLE
Mobile wallet functionality.

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Voting_DApp#3]
The submit vote button does not have functionality with the Algorand Mobile wallet. Pressing the button does not submit the vote or the Choice.

<img width="520" alt="Screen Shot 2021-12-20 at 3 43 19 PM" src="https://user-images.githubusercontent.com/43055154/146847471-2694f0de-1803-42c5-8390-776424ae7499.png">

**Comment by Bhaney44** [comment]
<img width="458" alt="Screen Shot 2021-12-20 at 3 57 52 PM" src="https://user-images.githubusercontent.com/43055154/146848257-d16dc52d-12a8-4c89-850a-f905c575bf0a.png">

**Comment by Bhaney44** [comment]
<img width="467" alt="Screen Shot 2021-12-20 at 4 17 48 PM" src="https://user-images.githubusercontent.com/43055154/146849836-04a03879-b9b1-4e92-ba3c-78bdcdef6262.png">

**Comment by ChoiceCoin** [comment]
I got this working in Safari with the Algorand mobile wallet.

**Comment by Bhaney44** [comment]
This also worked in Chrome.
